# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
defaults:
  run:
    shell: msys2 {0}

jobs:
  build:

    runs-on: windows-2019
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        msystem: mingw64
        install: patch  
        pacboy: nodejs:x
    - uses: actions/checkout@v3
      with:
         submodules: true
         fetch-depth: 15
         ref: master
    - name: Test npm
      run: |
        ./generator.sh
        npm install .
        npm run build 
        npm test
    - name: Upload interpreter.umd.js as artifact
      uses: actions/upload-artifact@v2
      with:
        name: interpreter
        path: |
          ./interpreter.umd.js
          ./js-interpreter.js
